import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    color: '#0f0f0f',
    backgroundColor: '#0f0f0f',
  },
  mainText: {
    marginTop: 15,
    alignItems: 'center',
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  inputView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputSize: {
    width: 100,
    margin: 15,
    marginVertical: 10,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    border: 'solid',
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderRadius: 5,
    fontFamily: 'monospace',
    fontSize: 25,
    textAlign: 'center',
  },
  inputData: {
    width: 100,
    margin: 15,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    border: 'solid',
    borderRadius: 5,
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    fontFamily: 'monospace',
    fontSize: 25,
    textAlign: 'center',
    outline: 'none',
  },
  button: {
    margin: 15,
    padding: 5,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    border: 'solid',
    borderRadius: 5,
    fontFamily: 'monospace',
    fontSize: 25,
    transition: 200,
  },
  field: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  fieldCellX: {
    display: 'flex',
    flexDirection: 'row',
  },
  cell: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#c6e6e9',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cellC: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#69dbe6',
    color: '#69dbe6',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cellB: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#e66969',
    color: '#e66969',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell1: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#4470e7',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell2: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#4bc04b',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell3: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#bb4848',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell4: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#243c69',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell5: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#e6a569',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell6: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#46b9b4',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell7: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#353535',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell8: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#e669dc',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cellF: {
    height: 55,
    width: 55,
    margin: 5,
    backgroundColor: '#e7b2c8',
    color: '#e7b2c8',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
})
