import { StyleSheet, Dimensions } from 'react-native'

export const styles = StyleSheet.create({
  mainViewPortrait: {
    flex: 1,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    color: '#080808',
    backgroundColor: '#080808',
  },
  mainViewLandscape: {
    flex: 1,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#080808',
    backgroundColor: '#080808',
  },
  mainText: {
    margin: 10,
    marginTop: 25,
    alignItems: 'center',
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 25,
  },
  inputView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputData: {
    width: 85,
    margin: 5,
    marginHorizontal: 5,
    backgroundColor: '#080808',
    color: '#c6e6e9',
    borderColor: '#c6e6e9',
    borderRadius: 5,
    borderWidth: 2,
    fontFamily: 'monospace',
    fontSize: 20,
    textAlign: 'center',
  },
  active: {
    color: '#69dbe6',
    borderColor: '#69dbe6',
  },
  buttonView: {
    margin: 5,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#c6e6e9',
    borderRadius: 5,
  },
  button: {
    padding: 5,
    backgroundColor: '#080808',
    color: '#c6e6e9',
    textAlign: 'center',
    fontFamily: 'monospace',
    fontSize: 25,
  },
  viewInfo: {
    width: 300,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textInfo: {
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 13,
  },
  field: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  fieldCellX: {
    display: 'flex',
    flexDirection: 'row',
  },
  cell: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#c6e6e9',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cellText: {
    color: '#c6e6e9',
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 20,
  },
  resultView: {
    padding: 10,
    paddingLeft: 25,
    paddingRight: 25,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#080808',
    color: '#c6e6e9',
    borderWidth: 3,
    borderColor: '#c6e6e9',
    borderRadius: 5,
    position: 'absolute',
    zIndex: 1,
  },
  resultWin: {
    color: '#4bc04b',
    fontFamily: 'monospace',
    fontSize: 40,
  },
  resultLose: {
    color: '#e66969',
    fontFamily: 'monospace',
    fontSize: 50,
  },
  resultText: {
    margin: 10,
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 25,
  },
  resultButton: {
    margin: 15,
    borderWidth: 3,
    borderColor: '#c6e6e9',
    borderRadius: 5,
  },
  errorText: {
    fontFamily: 'monospace',
    color: '#e66969',
  },
})
