import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    color: '#0f0f0f',
    backgroundColor: '#0f0f0f',
  },
  mainText: {
    margin: 10,
    marginTop: 25,
    alignItems: 'center',
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 25,
  },
  inputView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputSize: {
    width: 80,
    margin: 10,
    marginHorizontal: 10,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    borderColor: '#c6e6e9',
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderRadius: 5,
    fontFamily: 'monospace',
    fontSize: 20,
    textAlign: 'center',
  },
  inputData: {
    width: 80,
    margin: 10,
    marginHorizontal: 10,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    borderColor: '#c6e6e9',
    borderRadius: 5,
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    fontFamily: 'monospace',
    fontSize: 20,
    textAlign: 'center',
  },
  buttonView: {
    borderColor: '#c6e6e9',
    border: 'solid',
    borderRadius: 5,
  },
  button: {
    margin: 5,
    padding: 5,
    backgroundColor: '#0f0f0f',
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 25,
    transition: 200,
  },
  viewInfo: {
    width: 300,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textInfo: {
    color: '#c6e6e9',
    fontFamily: 'monospace',
    fontSize: 10,
  },
  field: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  fieldCellX: {
    display: 'flex',
    flexDirection: 'row',
  },
  cell: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#c6e6e9',
    color: '#c6e6e9',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cellC: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#69dbe6',
    color: '#69dbe6',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cellB: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#e66969',
    color: '#e66969',
    border: 'none',
    borderRadius: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 35,
  },
  cell1: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#4470e7',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell2: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#4bc04b',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell3: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#bb4848',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell4: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#243c69',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell5: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#e6a569',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell6: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#46b9b4',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell7: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#353535',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cell8: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#e669dc',
    border: 'none',
    borderRadius: 5,
    justifyContent: 'center',
  },
  cellF: {
    height: 35,
    width: 35,
    margin: 3,
    backgroundColor: '#516368',
    border: 'none',
    borderRadius: 5,
  },
  cellText: {
    color: '#c6e6e9',
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'monospace',
    fontSize: 20,
  }
})
